"use client";

import React, { useState } from "react";
import { Container } from "@/components/ui/Container";
import { FadeIn } from "@/components/ui/FadeIn";
import { ArrowRight, Bot, Database, Mail, MessageCircle, Users, Workflow, CheckCircle2 } from "lucide-react";
import { cn } from "@/lib/utils";
import { siteConfig } from "@/config/site";
import { motion, AnimatePresence } from "framer-motion";

const servicesList = [
  { id: "leads", title: "Lead Management Automation", icon: Users, summary: "Capture enquiries, qualify them against your criteria, and route complete lead records to the right sales owner.", details: ["Website and form intake", "AI-assisted qualification", "CRM record creation", "Sales notifications and follow-up"] , diagram: { from: "Form / Ad Lead", process: "Qualification Rules", to: "CRM + Sales Alert" } },
  { id: "support", title: "WhatsApp & Support Automation", icon: MessageCircle, summary: "Give customers quick answers from approved business information while sending sensitive or complex conversations to a person.", details: ["WhatsApp Business flows", "Knowledge-base responses", "Intent and priority routing", "Human handoff paths"] , diagram: { from: "Customer Message", process: "AI + Knowledge Base", to: "Reply or Handoff" } },
  { id: "crm", title: "CRM & Sales Automation", icon: Workflow, summary: "Keep pipeline stages, tasks, and notifications aligned so sales teams have the context they need without manual updates.", details: ["Pipeline stage updates", "Task and owner assignment", "Event-triggered alerts", "Cross-tool data sync"] , diagram: { from: "Sales Event", process: "Rules + Enrichment", to: "CRM Action" } },
  { id: "data", title: "Data & Reporting Automation", icon: Database, summary: "Move information from forms, spreadsheets, and systems into a consistent reporting workflow your team can trust.", details: ["Structured data collection", "Validation and deduplication", "Scheduled reporting flows", "Exception notifications"] , diagram: { from: "Source Data", process: "Validate + Transform", to: "Report / Database" } },
  { id: "email", title: "Email Automation", icon: Mail, summary: "Coordinate confirmations, internal alerts, and follow-up messages around the events already happening in your business.", details: ["Event-based email triggers", "Personalised templates", "Internal routing", "Follow-up sequences"] , diagram: { from: "Business Event", process: "Template + Rules", to: "Relevant Inbox" } },
  { id: "custom", title: "Custom AI Workflows", icon: Bot, summary: "Design a focused workflow around your process, tools, and decision points when an off-the-shelf recipe is not enough.", details: ["Custom prompts and guardrails", "API and webhook connections", "Approval and fallback steps", "Documented handover"] , diagram: { from: "Your Workflow", process: "AI + Orchestration", to: "Configured Outcome" } },
];

export function Services() {
  const [selectedService, setSelectedService] = useState(0);
  const activeService = servicesList[selectedService];
  const Icon = activeService.icon;
  return <section id="services" className="py-24 bg-[#080a0f] border-t border-slate-800/60 relative"><Container>
    <div className="text-center max-w-3xl mx-auto mb-16"><FadeIn direction="down" delay={0.1}><span className="text-xs font-mono uppercase tracking-widest text-cyan-400 px-3 py-1 rounded-full bg-cyan-400/10 border border-cyan-400/20 inline-block mb-4">Services</span></FadeIn><FadeIn direction="up" delay={0.2} preset="blur"><h2 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight mb-4">Automation built around <span className="bg-gradient-to-r from-cyan-400 to-blue-500 bg-clip-text text-transparent">your workflow.</span></h2></FadeIn><FadeIn direction="up" delay={0.3}><p className="text-slate-400 text-base sm:text-lg">From first enquiry to internal reporting, we connect the steps that currently depend on copy-paste, inbox searching, or manual follow-up.</p></FadeIn></div>
    <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start"><div className="lg:col-span-5 space-y-2">{servicesList.map((service, index) => { const ServiceIcon = service.icon; const isSelected = selectedService === index; return <motion.button key={service.id} onClick={() => setSelectedService(index)} whileHover={{ x: 4 }} className={cn("w-full text-left p-4 rounded-xl border transition-all duration-300 flex items-center gap-4 group cursor-pointer", isSelected ? "bg-slate-800/80 border-cyan-500/50 shadow-[0_0_20px_rgba(0,240,255,0.15)] text-white" : "bg-slate-900/30 border-slate-800/60 text-slate-400 hover:bg-slate-800/40 hover:text-slate-200")}><div className={cn("w-10 h-10 rounded-lg flex items-center justify-center shrink-0 border", isSelected ? "bg-cyan-400/20 border-cyan-500/40 text-cyan-400" : "bg-slate-950 border-slate-800 text-slate-500 group-hover:text-slate-300")}><ServiceIcon className="w-5 h-5" aria-hidden="true" /></div><span className="flex-1 min-w-0 text-sm font-semibold">{service.title}</span><ArrowRight className={cn("w-4 h-4 transition-transform shrink-0", isSelected ? "text-cyan-400 translate-x-1" : "text-slate-600")} aria-hidden="true" /></motion.button>; })}</div>
    <div className="lg:col-span-7 p-6 sm:p-8 rounded-2xl bg-slate-900/50 border border-slate-800 backdrop-blur-xl shadow-2xl lg:sticky lg:top-28"><AnimatePresence mode="wait"><motion.div key={selectedService} initial={{ opacity: 0, scale: 0.98 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.98 }} transition={{ duration: 0.3 }}><div className="flex items-center gap-3 mb-4"><div className="w-12 h-12 rounded-xl bg-cyan-400/10 border border-cyan-500/30 flex items-center justify-center text-cyan-400"><Icon className="w-6 h-6" aria-hidden="true" /></div><div><span className="text-xs font-mono text-cyan-400 uppercase tracking-wider">Service 0{selectedService + 1}</span><h3 className="text-2xl font-bold text-white">{activeService.title}</h3></div></div><p className="text-slate-300 text-base leading-relaxed mb-6">{activeService.summary}</p><div className="p-4 rounded-xl bg-slate-950 border border-slate-800 mb-6"><span className="text-xs font-mono text-slate-500 uppercase block mb-3">Typical flow</span><div className="flex flex-col sm:flex-row items-center justify-between gap-2 text-xs font-mono"><div className="p-2.5 rounded bg-slate-900 border border-slate-800 text-slate-300 text-center w-full sm:flex-1">{activeService.diagram.from}</div><ArrowRight className="w-4 h-4 text-cyan-400 rotate-90 sm:rotate-0" aria-hidden="true" /><div className="p-2.5 rounded bg-cyan-950/40 border border-cyan-500/40 text-cyan-400 font-semibold text-center w-full sm:flex-1">{activeService.diagram.process}</div><ArrowRight className="w-4 h-4 text-cyan-400 rotate-90 sm:rotate-0" aria-hidden="true" /><div className="p-2.5 rounded bg-slate-900 border border-slate-800 text-slate-300 text-center w-full sm:flex-1">{activeService.diagram.to}</div></div></div><div className="space-y-3 mb-8"><h4 className="text-xs font-mono uppercase text-slate-400 tracking-wider">What this can include</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{activeService.details.map((detail) => <div key={detail} className="flex items-start gap-2.5 text-xs text-slate-300"><CheckCircle2 className="w-4 h-4 text-cyan-400 shrink-0" aria-hidden="true" /><span>{detail}</span></div>)}</div></div><a href="#contact" className="inline-flex items-center justify-center gap-2 w-full py-3 px-5 rounded-lg bg-cyan-400 text-slate-950 font-semibold text-sm hover:bg-cyan-300 transition-colors"><span>Discuss this workflow</span><ArrowRight className="w-4 h-4" aria-hidden="true" /></a></motion.div></AnimatePresence></div></div>
  </Container></section>;
}
